### ISSUE TITLE
postgres case insensitive column names

### ISSUE THREAD

**Issue by DavidBadura** [patchlevel/event-sourcing#165]
Postgres columns always seem to be created in lowercase. Saving the data works without any problems. But when reading you get the column names in lowercase.

Example:

`recordedOn` => `recordedon`

There is then an error when accessing the array. Another field is also affected: `aggregateId`.

The solution would be to create the columns in `lowersnakecase`. But that would be a **BC break** because you would have to adapt the scheme.

Otherwise you would have to fix the data in the store so that the data can be loaded from Postgres.

**Comment by DanielBadura** [comment]
Since this is a bug i wouldnt mind having a bc but the should first check if the get this fixed without bc

**Comment by DavidBadura** [comment]
looks like we can fix this with adding this condition in `normalizeResult`

```php
        if (isset($result['aggregateid']) && isset($result['recordedon'])) {
            $result['aggregateId'] = $result['aggregateid'];
            $result['recordedOn'] = $result['recordedon'];

            unset($result['aggregateid'], $result['recordedon']);
        }
```

for the 2.x release, we should change the schema to lower snakecase
