### ISSUE TITLE
add test helper functions for phpunit

### ISSUE THREAD

**Issue by DavidBadura** [patchlevel/event-sourcing#214]
We should support aggregate testing. It is difficult to work with messages and the messages are irrelevant for the aggregates themselves. It's all about events. We can offer following methods for phpunit:

```php
/** 
 * @template T of object
 * @param class-string<T> $aggregateClass
 * @param array<object> $events
 * @return T
 */
public static function createAggregateFromEvents(string $aggregateClass, array $events): object;

/** 
 * @param array<object> $events
 */
public static function assertRecordedEvents(AggregateRoot $aggregate, array $events): void;
```

This could be offered as a trait analogous to prophesize.

**Comment by DanielBadura** [comment]
Closing as it seems to be not needed anymore right now with version 2.
