### ISSUE TITLE
improve phpbenchmark output / report

### ISSUE THREAD

**Issue by DavidBadura** [patchlevel/event-sourcing#254]
Currently the output from the benchmark is difficult to read and has information in it that we don't need. eg. the diagram can be removed. Maybe we can get a better output here.

**Comment by DanielBadura** [comment]
Or maybe move the information. Ref: https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

But this would be maybe more work, or we need to implement an own summary thing for phpbench.

**Comment by DavidBadura** [comment]
why "or"? For me these are two different tasks. What is give out and where it is give out.

**Comment by DanielBadura** [comment]
Which or do you mean now? :D

What i meant is: 

Maybe it's worth to remove our comment implementation and move the information to the new summary. There it could be nice to still have the information we now deliver, like the graphs.

If the dont want the graphs then we could a) try to strip the output or b) create a summary (i think this is called like this) for phpbench.

Other thing would be to have both, the comment & a job summary.
