### ISSUE TITLE
Documentation update workflow is currently not working correctly

### ISSUE THREAD

**Issue by DanielBadura** [patchlevel/event-sourcing#302]
See: https://github.com/patchlevel/event-sourcing/runs/7579745095?check_suite_focus=true#step:7:28

**Comment by icanhazstring** [comment]
Shouldn't the script refer to `context.ref_name`? 
As per documentation: [here](https://docs.github.com/en/actions/learn-github-actions/contexts#example-contents-of-the-github-context)

Edit: A, just saw. We only want the `major.minor` part for the docs.

**Comment by DanielBadura** [comment]
Yeah we could also take `context.ref_name` instead of `context.ref` but it makes no real difference here i think. I think the errors comes from that the regex doesnt match anything since we expect an `x` in the `ref` which could be not right in the release context. But this is just a thought since i did not look into it so far.

And yes, we want only to have `major.minor` because we dont provide extra docs for patch releases.

**Comment by icanhazstring** [comment]
Ah got it. So the regex did try to match the latest released version `2.0.2` right?
So we need to expand the regex to match every `.x` branch and also tagged versions.

I might have some minutes to create a small PR. Testing it is always kind of difficult tho :D

**Comment by DavidBadura** [comment]
Should work now, thanks again @icanhazstring.
