### ISSUE TITLE
Combine schema manipulation with doctrine?

### ISSUE THREAD

**Issue by icanhazstring** [patchlevel/event-sourcing#316]
Hi,

I am currently using this library in conjunction with doctrine/orm. The issue however is, that writing functional tests using real database is not working properly if I am also using zenstruck/foundry. Which is providing a `ResetDatabase` trait that more or less runs a `doctrine:schema:drop` and `doctrine:schema:create` in between tests.

Having that, the `event-sourcing:schema:drop` and `create` is obviously not working.
Right now I have created my command replacements using a combination of both like this:

```php
use Doctrine\Bundle\DoctrineBundle\Command\Proxy\DropSchemaDoctrineCommand;
use Doctrine\ORM\Tools\Console\EntityManagerProvider;
use Patchlevel\EventSourcing\Console\Command\SchemaDropCommand;
...

#[AsCommand(
    name: 'doctrine:schema:drop',
    description: 'Executes (or dumps) the SQL needed to drop the database schema',
)]
final class DoctrineSchemaDropCommand extends Command
{
    private DropSchemaDoctrineCommand $dropSchemaDoctrineCommand;

    public function __construct(
        EntityManagerProvider $entityManagerProvider,
        private readonly SchemaDropCommand $eventSourcingSchemaDropCommand
    ) {
        parent::__construct();
        $this->dropSchemaDoctrineCommand = new DropSchemaDoctrineCommand($entityManagerProvider);
    }

    public function run(InputInterface $input, OutputInterface $output): int
    {
        $exitCode = $this->dropSchemaDoctrineCommand->run(
            new ArrayInput(
                $this->filterOptions($input, $this->dropSchemaDoctrineCommand),
                $this->dropSchemaDoctrineCommand->getDefinition()
            ),
            $output
        );

        if ($exitCode > 0) {
            return $exitCode;
        }

        return $this->eventSourcingSchemaDropCommand->run(
            new ArrayInput(
                $this->filterOptions($input, $this->eventSourcingSchemaDropCommand),
                $this->eventSourcingSchemaDropCommand->getDefinition()
            ),
            $output
        );
    }

    /**
     * @return array<string, mixed>
     */
    private function filterOptions(InputInterface $input, Command $command): array
    {
        /** @var array<string, mixed> $options */
        $options = [];

        foreach ($command->getDefinition()->getOptions() as $inputOption) {
            $optionName = '--'.$inputOption->getName();
            /** @psalm-suppress MixedAssignment */
            $options[$optionName] = $input->getParameterOption($optionName) ?? true;
        }

        return array_filter($options);
    }
}
```

So running `doctrine:schema:drop` will now execute both doctrine and event-sourcing commands.
Could this be integrated into your package somehow? Or would it even make sense?

**Comment by DanielBadura** [comment]
I guess you are using the same connection then for the ORM and event sourcing part? If yes, you could try with using this bundle here https://github.com/dmaicher/doctrine-test-bundle which is IMHO better then the default approach foundry uses to reset the database. If you enable the bundle then foundry switches the behaviour AFAIK. Then you would need to setup the database in the `bootstrap.php` and before each test a transaction gets created which is later rollbacked. This should also be much faster than the current reset strategy. If your projections also use the same connection then this topic is also solved with that. If not you would need to take care about that manually. Maybe we can improve that in the future at this topic or hint at the documentation about that.

To the part about mixing ORM and event sourcing schema stuff: As you know, you shouldn't manipulate the event sourcing database, so the only way to safely migrate and update your software is to copy the database. In this step you can change the events, test them safely and then switch. Now if we have other tables in this database, it won't be that easy anymore. You need to copy these tables too. Therefore we recommend splitting the database in production. But it is fine for testing purposes though.

We also wanted to make the schema management more flexible, which is coming soon. There we aim to be able to mix our schema with e.g. the ORM schema. Here is the open PR: #317

**Comment by icanhazstring** [comment]
Thanks. I already had in mind a quicker way to "reset" the db. Thanks for the link to the doctrine bundle.

Maybe I can find a way to add this into foundry itself. As I try to keep the deps at a minimum.

Looking forward to the PR you linked 💪
Questions answered 😉

**Comment by DavidBadura** [comment]
With version 2.1 it is now possible to merge the Doctrine ORM schema with the Eventsourcing schema:

https://patchlevel.github.io/event-sourcing-bundle-docs/2.1/store/#merge-orm-schema
