### ISSUE TITLE
events playhead start at 0 or 1?

### ISSUE THREAD

**Issue by DavidBadura** [patchlevel/event-sourcing#32]
Actually in the computer world indexes always start at 0, but i think playhead should start at 1. Like autoincrement.

Then we get the -1 out of our source code, which looks strange or like a magic number.

**Comment by DanielBadura** [comment]
We can actually have both. If the start the playhead at `0` and increment it after handling an event, or not?

**Comment by DavidBadura** [comment]
playhead should show the current value, not the next value.

```
$user = User::create(); // one event was released
$user->playhead(); // current playhead index, currently 0
```

according to your suggestion it would be `1`. you have to reduce the index in the method to get 0. however, this logic has to be implemented elsewhere, since the property is also accessed directly (snapshot).

if we just start the event index at 1, then we don't have these problems. And as i said, i think it is more logical to talk about the first event than the zero.
