### ISSUE TITLE
DoctrineSubscriptionStore does not handle long error messages

### ISSUE THREAD

**Issue by gzumba** [patchlevel/event-sourcing#609]
When the exception message is too long, the store fails:

`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255)`

This should be handled either by making the field a varchar without specified length (preferable) or truncating the error message.

I can make a PR for this, if wanted.

**Comment by DanielBadura** [comment]
Yes, it should not crash there. Which DB are you using?

**Comment by gzumba** [comment]
I am using Postgresql.

My quick fix to continue upgrade refactoring, was this:
`'error_message' => $subscriptionError ? u($subscriptionError->errorMessage)->truncate(255)->toString() : null,`

But having an unlimited varchar there would be better.

**Comment by DanielBadura** [comment]
Yes I agree, unlimited would be better to really understand what caused the error. WIll have a look into it
